### ISSUE TITLE
double check RA breathy j

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#102]
njm-ra  njm-ra-3    j̤     njm is the only language in RA to have j̤ so I'm inclined to assume that agg is correct here (otherwise why would RA have that column to begin with?)

**Comment by drammock** [comment]
just to be clear, is breathy j, not voiceless j

**Comment by bambooforest** [comment]
This symbol is described as "palatal voiced aspirated stop", which our conventions encode as <j̤> and not <jʰ>, so this is correct in RA. Closing.

**Comment by drammock** [comment]
wait...  if it's a *stop* then it should be ɟ̤ not j̤ right?

**Comment by bambooforest** [comment]
Yes, no worries. The symbol in the source is <j> but in the raw data we use: <ɟ> and <ɟ̤>. And for the for palatal glide in the raw source <y> we use <j> and its aspirated counterpart <j̤>.

This PR is ready to go.

**Comment by davidainman** [comment]
I am reopening this because there are still examples in the published data that have segments like "dʰ", "nʰ", "rʰ" which should be disallowed (expected: dʱ, nʱ, rʱ). Example languages: Korku, Bhojpuri, Kisiei.

**Comment by drammock** [comment]
> I am requesting this be reopened

Not reopening, will follow up this issue in #346.
