### ISSUE TITLE
OLAC metrics

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#113]
http://www.language-archives.org/checks/phoible.org

**Comment by drammock** [comment]
I'm pretty sure I fixed all these already. Try searching for any of them in
the generated Rdata file. OLAC just doesn't know about the changes because
they're not pushed to CLLD yet.

**Comment by bambooforest** [comment]
note to self: revisit any remaining issues in the latest OLAC integrity checks before next release:

http://www.language-archives.org/checks/phoible.org

**Comment by bambooforest** [comment]
Agreed. These codes have been updating. Closing.
