### ISSUE TITLE
Ubangi and not Adamawa

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#116]
WALS genus of 

http://phoible.org/languages/bfl 
http://phoible.org/languages/bbp

are Ubangi and not Adamawa

**Comment by bambooforest** [comment]
WALS genera are updated from time-to-time and the current version of phoible online has a historic version.

https://github.com/clld/wals-data/issues?q=is%3Aissue+is%3Aclosed

From RF, something to consider:

So the question for databases referencing WALS genera becomes: What do they want to indicate? "Historic" WALS genera, i.e. the classification as it was at some point in time? This would be the case, if some important analyses from the database did include the WALS genera as parameter.
Or are the WALS genera more a navigational device? In this case, the most recent WALS classification would be the best option.
What do you think is the case for PHOIBLE? If the latter, I'd even recommend dropping WALS genera, and only refer to Glottolog, where we may find a better long-term solution to the moving-target problem with WALS genera.

**Comment by drammock** [comment]
I'd say the genera are potentially part of analysis (our Language paper
used them that way). My choice would be to incorporate the WALS genera in
the Phoible repos so that they are tracked and can be updated with
successive releases without compromising reproducibility.

**Comment by bambooforest** [comment]
We've decided not to include genealogical information in releases of phoible because they can be gotten from Glottolog. Closing this issue.
