### ISSUE TITLE
wrong language code for Madi

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#120]
A Grammar of Ma’di by Blackings, Mairi, and Fabb

is not the Madi spoken in Papua New Guinea, but perhaps:

http://www.ethnologue.com/language/mhi

**Comment by bambooforest** [comment]
This language is indeed ISO [mhi] and Glottolog entry:

http://glottolog.org/resource/languoid/id/madi1260

Closing.

**Comment by drammock** [comment]
so, this was correct in the raw data all along?

**Comment by bambooforest** [comment]
yes. i've gotten several change requests via email and not all actually need changing. but it's great that people send these things.
