### ISSUE TITLE
Some missing codes in inventoryids_iso_gcode.csv

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#121]
1906,gny,
1970,qpt,
1999,adc,
2143,psx,
2150,yrm,

resolved to:

1906,pue,puel1244
1970,gvp,para1315
1999,mcd,shar1245
2143,tuo,pisa1245
2150,wca,yaro1235

- there is no ISO code for Pisamera, so I took the "language" which has it as a dialect -- here Glottolog is more detailed than ISO/Ethno
- yaro1235 is more detailed than the corresponding qca

**Comment by bambooforest** [comment]
@drammock i want to update these codes in this repo, so I should do here:

https://github.com/phoible/dev/blob/master/mappings/InventoryID-ISO-gcode-Bibkey-Source.tsv

or? Is there any point in maintaining:

https://github.com/phoible/dev/blob/master/mappings/InventoryID-BibtexKey.tsv
https://github.com/phoible/dev/blob/master/mappings/InventoryID-ISO-gcode.tsv

since they can be derived from the former and aren't called in any of the scripts.

**Comment by drammock** [comment]
I think the smaller tables can go away; they were used to create the bigger table, which is more useful and should be our primary point of maintenance going forward.
