### ISSUE TITLE
Update language name

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#122]
http://phoible.org/languages/skr

"Seraiki"

source says:

"Shackle, C. 1976. The Siraiki Language of Central Pakistan: A Reference Grammar. Unwin Brothers Limited."

**Comment by saraiki** [comment]
This language be renamed as Saraiki see http://www.ethnologue.com/language/skr

**Comment by bambooforest** [comment]
According to the Ethnologue, there are several alternative names for Saraiki including:

Bahawalpuri
Multani
Riasiti
Seraiki
Siraiki

We have used the language name Siraiki because that is the language name used in the grammar from which we identified the phoneme inventory:

https://books.google.ch/books/about/The_Siraiki_Language_of_Central_Pakistan.html?id=6cpjAAAAMAAJ&redir_esc=y

http://www.amazon.com/The-Siraiki-language-Central-Pakistan/dp/0728600269

http://journals.cambridge.org/action/displayFulltext?type=1&fid=3777928&jid=BSO&volumeId=40&issueId=03&aid=3777924

http://www.worldcat.org/title/siraiki-language-of-central-pakistan-a-reference-grammar/oclc/21903562

We may change the language name on the website when we update the website sometime in 2016.

Thanks!

**Comment by saraiki** [comment]
Thanks

**Comment by saraiki** [comment]
kindly this also be renamed in page  http://crubadan.org/languages/skr

**Comment by bambooforest** [comment]
Sorry, you will have to contact Kevin Scannell. We do not have access to the Crubadan website.

**Comment by saraiki** [comment]
ok

**Comment by drammock** [comment]
closed by #170
