### ISSUE TITLE
Two small errors in data

### ISSUE THREAD

**Issue by gnutz** [phoible/dev#128]
Hello,

I found two small errors in your data:

1. In the [aggregated 2014 release](https://github.com/phoible/dev/releases/tag/v2014), the file _phoible-phonemes.tsv_ shows the Language **Indonesian** (source GM) with the wrong language code. It should be **ind** and not **idn**.
2. The entry for Yanyuwa (source UPSID) in the online repository shows the source name: YANYPHA. However, in the UPSID database found [here](http://web.phonetik.uni-frankfurt.de/upsid), the source name is: YANYUWA

**Comment by drammock** [comment]
Thanks!  It looks like both of those issues have been fixed already in the current master branch, and will be incorporated in the next release.
