### ISSUE TITLE
output of orderIPA function

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#142]
i get something like this:

Warning: Unfamiliar glyph components. Phone: <ã> Codepoint: <Unfamiliar glyph components. Phone: <ã> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <bʲ> Codepoint: <Unfamiliar glyph components. Phone: <bʲ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ɕ> Codepoint: <Unfamiliar glyph components. Phone: <ɕ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <dʲ> Codepoint: <Unfamiliar glyph components. Phone: <dʲ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <dz̪> Codepoint: <Unfamiliar glyph components. Phone: <dz̪> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <e̞ː> Codepoint: <Unfamiliar glyph components. Phone: <e̞ː> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ə> Codepoint: <Unfamiliar glyph components. Phone: <ə> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ɛ̃> Codepoint: <Unfamiliar glyph components. Phone: <ɛ̃> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ɛː> Codepoint: <Unfamiliar glyph components. Phone: <ɛː> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ɡʲ> Codepoint: <Unfamiliar glyph components. Phone: <ɡʲ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <iː> Codepoint: <Unfamiliar glyph components. Phone: <iː> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <i̯e̞> Codepoint: <Unfamiliar glyph components. Phone: <i̯e̞> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <lʲ> Codepoint: <Unfamiliar glyph components. Phone: <lʲ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <nʲ> Codepoint: <Unfamiliar glyph components. Phone: <nʲ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <œ> Codepoint: <Unfamiliar glyph components. Phone: <œ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <œː> Codepoint: <Unfamiliar glyph components. Phone: <œː> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ɔ̃> Codepoint: <Unfamiliar glyph components. Phone: <ɔ̃> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ɔː> Codepoint: <Unfamiliar glyph components. Phone: <ɔː> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <sʲ> Codepoint: <Unfamiliar glyph components. Phone: <sʲ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ʃ> Codepoint: <Unfamiliar glyph components. Phone: <ʃ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <uː> Codepoint: <Unfamiliar glyph components. Phone: <uː> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ɯ̯ɤ̞> Codepoint: <Unfamiliar glyph components. Phone: <ɯ̯ɤ̞> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ɯi̯> Codepoint: <Unfamiliar glyph components. Phone: <ɯi̯> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <yː> Codepoint: <Unfamiliar glyph components. Phone: <yː> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <z> Codepoint: <Unfamiliar glyph components. Phone: <z> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ʑ> Codepoint: <Unfamiliar glyph components. Phone: <ʑ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: <ʒ> Codepoint: <Unfamiliar glyph components. Phone: <ʒ> Codepoint: >
Warning: Unfamiliar glyph components. Phone: dẑ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: d̪ᶻʲ Codepoint: ᶻ
Warning: Unfamiliar glyph components. Phone: dẑʷ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: ɿ Codepoint: ɿ
Warning: Unfamiliar glyph components. Phone: ɿ̰ Codepoint: ɿ
Warning: Unfamiliar glyph components. Phone: ɿ̹ Codepoint: ɿ
Warning: Unfamiliar glyph components. Phone: ɿˠ Codepoint: ɿ
Warning: Unfamiliar glyph components. Phone: ŝ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: ŝʷ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: ŝʼ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: ŝʼʷ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: ʅ Codepoint: ʅ
Warning: Unfamiliar glyph components. Phone: ʅ̹ Codepoint: ʅ
Warning: Unfamiliar glyph components. Phone: tˢ Codepoint: ˢ
Warning: Unfamiliar glyph components. Phone: tŝʰ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: t̪ˢʲ Codepoint: ˢ
Warning: Unfamiliar glyph components. Phone: tŝʷ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: tŝʷʰ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: tŝʷʼ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: tŝʼ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: ẑ Codepoint: ̂
Warning: Unfamiliar glyph components. Phone: ẑʷ Codepoint: ̂

which looks great, but codepoint is a term for the numerical value that represents the unicode character. it would be great to write the code points value as part of the error message, e.g. 

Warning: Unfamiliar glyph components. Phone: ẑʷ Codepoint: U+0302. Glyph: ̂

because the glyph (in particular diacritics) aren't always so easily discernible as output

**Comment by drammock** [comment]
oops. used to work but I broke it this morning. Change [this line here](https://github.com/bambooforest/phoible/blob/add-new-resources/aggregate-raw-data.R#L380) from `typ[missing]` to `codepoints(typ[missing])`
