### ISSUE TITLE
Finish EA and UZ segment updates

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#143]
a reminder to finish the EA segment-phoneme correspondences to make them follow phoible conventions

also, update any strange segments in UZ 2016 inventories

initial input data is being added in #140

also, will need to update the bibtex mapping file and add the latest and greatest references

**Comment by drammock** [comment]
In debugging the trump issue today, I noticed there are a lot of inventories within EA that have an ISO code of "0".  Any idea why?  Can you add that to the issues to fix when working on EA segments?

**Comment by bambooforest** [comment]
Thanks for the hot fix. Yes, this seems to be the authors way of noting that they don't know which ISO code to assign or that there is no appropriate ISO code. We have this issue with another dataset as well (with a different way of denoting missing | unknown code), so I plan to deal with these all together.

**Comment by drammock** [comment]
I suggest using "NA" rather than "0", my 2 cents.

**Comment by bambooforest** [comment]
I'm going to close this issue because it's part of a larger todo which includes making sure that all segments conform to our segment conventions. See issue #160
