### ISSUE TITLE
UTF-8 Encoding on Win 7 64 bit R 3.3.2

### ISSUE THREAD

**Issue by n31k** [phoible/dev#151]
Hello and nice job there! This issue has three points, but are all closely related to encoding. Thus I decided to put them all here together. 

1. I ran the `aggregation.R` file and encountered some errors due to encoding. I added `encoding="UTF-8"` in all `read.delim()` calls and the script run fine - except for the line adding feature columns to the `all.data` data frame, which I post in another issue. (Both issues are fixed in my local file).

2. Still, I had to comment out the `gsub` statements for "removing tiebars", which broke the script and also looked weird in my text editor. 

3. When I search for an IPA phoneme symbol, e.g. `all.data[grep('\u0275', all.data$Phoneme), 'LanguageName'] ` I don't get all the correct languages. Compare with `all.data[all.data$spaDescription=='theta', 'LanguageName']`

I think that I did not change the encoding of the script itself, but I am not sure that I have not set my text editor to set the encoding of `*.R` files automatically to UTF-8.

Thanks!

**Comment by bambooforest** [comment]
@drammock

**Comment by drammock** [comment]
I've reached the conclusion that I simply won't support the build scripts on Windows.  Getting R on Windows to handle Unicode gracefully is just too much work, and there's really no reason that we need the *build scripts* to be portable, as long as the resulting CSV and RData files are.  As long as Windows-using consumers of the data can load the .RData file (or load the .csv in python3 or some other framework that handles unicode well) then that's enough.
