### ISSUE TITLE
all.data data.frame : Indexing fails at level 2 error

### ISSUE THREAD

**Issue by n31k** [phoible/dev#152]
On R 3.3.2 Win7 64 bit.

L217 `all.data[upsid.disjunct.indices, feat.columns] <- upsid.feats[feat.columns]`

raises error for "nested indexing failing at level 2". I changed that to 

```r
all.data[, feat.columns] <- NA
all.data[upsid.disjunct.indices, feat.columns] <- upsid.feats[feat.columns]
```

which solved the problem. I am posting this just in case anyone needs it...

Thanks!

**Comment by bambooforest** [comment]
@drammock is this still an issue?

**Comment by drammock** [comment]
I'll have a look later in the week; my laptop runs linux so I need to use another machine to test

**Comment by drammock** [comment]
I've reached the conclusion that I simply won't support the build scripts on Windows.  Getting R on Windows to handle Unicode gracefully is just too much work, and there's really no reason that we need the *build scripts* to be portable, as long as the resulting CSV and RData files are.  As long as Windows-using consumers of the data can load the .RData file (or load the .csv in python3 or some other framework that handles unicode well) then that's enough.
