### ISSUE TITLE
Trump duplicates

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#156]
The trump procedure captures a unique list of inventories (by language code) determined by the trump hierarchy in the aggregate script when there are multiple inventories across sources, but it assigns TRUMP == True to all multiple entries (inventories) within a given source. This

final.data.trump <- final.data[final.data$Trump==TRUE,]

will still return multiple inventory descriptions belonging to the same "language".

**Comment by drammock** [comment]
Here's the output from the branch in #157 
```
R> trumped <- subset(all.data, Trump)
R> length(unique(all.data$InventoryID))
[1] 2628
R> length(unique(all.data$LanguageCode))
[1] 1845
R> length(unique(trumped$InventoryID))
[1] 1701
R> length(unique(trumped$LanguageCode))
[1] 1701
```
