### ISSUE TITLE
Korean lacks f

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#161]
Incredibly, this source shows a labiodental in Korean:

https://archive.org/details/rosettaproject_kor_phon-2

But when I went to the Handbook 1999 version and this column is empty.

Update in the raw data.

**Comment by drammock** [comment]
Just to clarify (confused by what "this source" refers to): the source (Handbook of the IPA) shows no `/f/` but the UZ raw data text file includes `/f/`. Solution is to delete that line from the raw data text file.

**Comment by bambooforest** [comment]
Yes indeed. I'll send you the source material because it's quite funny -- in the Handbook from 1993 they list /f/. In 1999 it's not there. (f)riday humor, apparently.

**Comment by drammock** [comment]
Huh. I looked it up in my copy yesterday too, and there was no /f/. I read through the whole entry and saw no mention of labiodentals anywhere even as allophones. So I'm definitely +1 for removing it. Do we need to double-check **all** the entries that came from the 1993 book now?

**Comment by bambooforest** [comment]
Yes, I will do so against the 1999 version and update any squibs accordingly.

**Comment by bambooforest** [comment]
This issue has been fixed. No Korean inventories have labiodentals. 

Regarding going through the entire handbook, this would be part of a larger project that involves data checking on a large-scale. I see no reason to do this at the moment.
