### ISSUE TITLE
identifying consonants and vowels

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#163]
is not as straightforward as it seems with the latest inventory additions. this may mean revisiting the inventories and conventionalizing their segment representations.

for example, not all vowels are caught by (syllabic %in% '+' & consonantal %in% '-') (e.g. segments that have syllabic -,+ in forms including /je/)

not all consonants are straightforwardly captured by (syllabic %in% '-') (e.g. syllabic consonants)

these circumstances create several corner cases for consideration

**Comment by drammock** [comment]
the broad classification into consonants and vowels does have a lot of corner cases (although the specific example of `je` shouldn't come up; diphthongs are supposed to be done with the non-syllabic diacritic like `i̯e`). Regardless of that specific example, `ɹ` is another problematic one (people disagree on whether it is C, V, or both).  So there are theoretical disagreements about what features `ɹ` should have, and then there are practical questions of how to cut inventories into Cs vs Vs based on the features.  I guess my question is: do we need to be able to do that *as devs/maintainers*?  End-users might want to cut C vs V cleanly, but it's up to them to look at the inventories and make sure they're getting the cut they expect, and adjust their cut criterion accordingly.

**Comment by bambooforest** [comment]
Agreed. Closing.
