### ISSUE TITLE
Merge indices

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#197]
@drammock 

I would like to merge these two files into the latter:

https://github.com/phoible/dev/blob/master/mappings/inventoryids_filenames.tsv
https://github.com/phoible/dev/blob/master/mappings/InventoryID-Bibtex.tsv

This shouldn't cause any problems and makes less clutter.

**Comment by drammock** [comment]
no objections, go for it.

**Comment by drammock** [comment]
closed by #199
