### ISSUE TITLE
Sesotho != Sissano

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#221]
https://phoible.org/inventories/view/1017

is labeled Sesotho (Demuth 1992), which is correct, but it's incorrectly tagged with with the Sissano (PNG) ISO & Glottolog codes:

https://glottolog.org/resource/languoid/id/siss1243

Update to:

https://glottolog.org/resource/languoid/id/sout2807

sout2807
sot

https://github.com/phoible/dev/blob/master/mappings/InventoryID-LanguageCodes.csv#L1018

**Comment by drammock** [comment]
closed by #223
