### ISSUE TITLE
Prenasalization vs nasal release

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#232]
@drammock - the immediate issue is what to do regarding the UPSID_IPA correspondences:

74	nd	ⁿd		nd	prenasalized voiced alveolar plosive	
75	dⁿ	dⁿ		dn	nasally-released voiced alveolar plosive

https://github.com/phoible/dev/blob/master/raw-data/UPSID/UPSID_IPA_correspondences.tsv#L75-L76

if I change /dⁿ/ -> /nd/, etc., we collapse a distinction in UPSID that apparently only exists in ARRERNTE (as discussed over email and summarized for this issue below). Given that ARRERNTE doesn't have a citation in UPSID and this would bring it more in-line with with phoible conventions, I'm OK with it.

Note also open issue #61 .

Regarding prenasalization vs nasal release in phoible, there are two issues.

```
load("phoible.RData")
library(dplyr)
phoible %>% filter(grepl("ⁿ", Phoneme)) %>% select(LanguageName, Phoneme, InventoryID)

          LanguageName Phoneme InventoryID
1             ARRERNTE      bⁿ         201
2             ARRERNTE      dⁿ         201
3             ARRERNTE      d̠ⁿ         201
4             ARRERNTE      d̪ⁿ         201
5             ARRERNTE      ɖⁿ         201
6             ARRERNTE      ɡⁿ         201
7    Caodeng rGyalrong      ⁿb        2257
8    Caodeng rGyalrong      ⁿd        2257
9    Caodeng rGyalrong     ⁿdz        2257
10   Caodeng rGyalrong     ⁿd̠ʒ        2257
11   Caodeng rGyalrong     ⁿɖʐ        2257
12   Caodeng rGyalrong      ⁿɡ        2257
13   Caodeng rGyalrong      ⁿɢ        2257
14   Caodeng rGyalrong      ⁿɟ        2257
...
```

1. ARRERNTE

- proposed change to mb, nt, etc.
- because the phonological analysis emphasizes that these are prenasalized stops, not sequences/clusters, which is why they avoid /mb/.  But in phoible all the contrastive segments are separated, so just the fact that we have an entry for /mb/ makes it clear that it's not a sequence/cluster.

2. EURPhon inventories

- propose change to mb, nt, etc.
- because EURPhon developers use nasal release superscript for prenasalization

**Comment by drammock** [comment]
> if I change /dⁿ/ -> /nd/, etc., we collapse a distinction in UPSID that apparently only exists in ARRERNTE

Assuming this was a typo, but just in case: do *not* change /dⁿ/ → /nd/.  "nasal release" should always use `ⁿ` after the base glyph (that is official IPA, we shouldn't try to do place-matching there, and we *definitely* shouldn't move the nasal marker from the right to the left side for "nasal release").

**Comment by bambooforest** [comment]
@drammock -- sorry i was in prenaslalization land! yes, i mean changing dⁿ -> dn, etc., in line with our conventions. this would not cause any loss of contrasts in the UPSID_IPA correspondences file and it would bring the Inventory ARRERNTE (UPSID 201):

https://phoible.org/inventories/view/201

more inline with Inventory Arrernte, Central (UZ 2158):

https://phoible.org/inventories/view/2158

**Comment by bambooforest** [comment]
Summary:

- UPSID values for ARRERNTE stay as are (superscript-n after a base glyph is "nasal release")
- conventionalizes use of superscript-n in EA (for prenasalization) to phoible conventions
