### ISSUE TITLE
Revisit word_language mapping

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#244]
We may have at some point decided not to infer from morpheme to word the language because of cases of multiple morpheme language values. We should perhaps revisit this since it's interesting linguistically (and typically thought to be improbable or rare, but see: https://www.frontiersin.org/articles/10.3389/fpsyg.2015.00082/full ). We could do something like infer the language of the morpheme as word when there is only one language, drop a term like "mixed" into word_language when there are multiple different languages per morphemes in a word. This would be interesting then to see what percentage, if at all, are mixed word forms.

**Comment by drammock** [comment]
@bambooforest I don't understand this issue.  Was it meant to be posted in a different repository?

**Comment by bambooforest** [comment]
Indeed!
