### ISSUE TITLE
semantic versioning

### ISSUE THREAD

**Issue by drammock** [phoible/dev#27]
I noticed on the release that it was tagged with version "v2014".  I understand this was probably motivated by Martin's preferences for CLLD releases being once a year at most.  However, phoible is still software, and as such I think it's worth considering, at least, whether we want a more fine-grained versioning scheme (personally I like [semantic versioning](http://semver.org/)).  The advantage of this is that if we (or others) use phoible in publications, and want to use the most current version (because of new data or features added since last CLLD release, for example), then we can create a new intermediate release that we can reference in that publication.  Thoughts?

**Comment by bambooforest** [comment]
@drammock - i think we can close this now that we follow semver in the latest (and for the future) version of phoible, with releases on zenodo
