### ISSUE TITLE
Duplicates?

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#312]
phoible %>% select(InventoryID, Phoneme) %>% group_by(InventoryID, Phoneme) %>% filter(n()>1)

  InventoryID Phoneme
        <int> <chr>  
1        2478 i̯ɔ     
2        2478 i̯ɔ

**Comment by drammock** [comment]
I just updated from master branch and I get 

```R
phoible %>% select(InventoryID, Phoneme) %>% group_by(InventoryID, Phoneme) %>% filter(n()>1)
# A tibble: 0 x 2
# Groups:   InventoryID, Phoneme [0]
# … with 2 variables: InventoryID <int>, Phoneme <chr>
```
