### ISSUE TITLE
Error in sources

### ISSUE THREAD

**Issue by tresoldi** [phoible/dev#314]
There is a small error in the Bibtex entry for `saphon`, a missing `"and"` that makes the entry invalid: on line 37 of https://github.com/phoible/dev/blob/master/data/phoible-references.bib we have `Michael, Lev, Tammy Stark, and Will Chang` instead of `Michael, Lev, *and* Tammy Stark, and Will Chang`.

It is the only error when parsing the whole the whole file. I cannot make a PR due to permissions.

**Comment by bambooforest** [comment]
Thanks @tresoldi . You should be able to make a PR after you've forked phoible dev.

**Comment by tresoldi** [comment]
Oh, I though you used branches, sorry. I'll make one right now.

**Comment by bambooforest** [comment]
We do use branches -- but only from forks. :)

**Comment by bambooforest** [comment]
Closed by #315
