### ISSUE TITLE
[Question] Multiple entries under the same ISO code

### ISSUE THREAD

**Issue by Lavmint** [phoible/dev#370]
Greetings, 

I'm making a small pet-project and noticed that for a single `ISO6393` could be multiple `InventoryID` with a different set of phonemes. For instance under ISO `rus` (russ1263) there are 3 entries (166, 530, 2261)

Could someone please explain me what does this mean and would it be correct to merge those entries into a single entity in my app under `rus` with total sounds of 118 or it's better to keep them separated? Also would it be correct to merge all allophones in the same entity?

Another question is: 
why some phonemes while having the same `GlyphID` can have different `Marginal` value?

**Comment by bambooforest** [comment]
@Lavmint -- all your questions should be answered in the FAQ:

https://phoible.org/faq

Whether you combine or keep the inventories separate is up to you and your application.

Marginal is a status indicator about a phoneme and is dependent on whether the source reports marginality of phonemes. Not all bibliographic sources report marginal (or borrowed) phonemes (or allophones). This may also be pertinent to your decision of whether you combine different sources or not.
