### ISSUE TITLE
make phoible an R package?

### ISSUE THREAD

**Issue by drammock** [phoible/dev#56]
Something to think about for the long-term.  It is possible to release R packages that are data sets only. It would be a nice distribution model (worldwide mirrors) with a built-in versioning and upgrade mechanism.  We could also release some purpose-built functions (trump, feature reduction, etc) along with it.  Thoughts?

**Comment by bambooforest** [comment]
I think this would be a cool project but not something we're taking on. OK to close @drammock ?

**Comment by drammock** [comment]
Closing. Nowadays R no longer defaults to `stringsAsFactors=TRUE` so there's little risk in distributing the dataset as a CSV.  I'd still entertain the idea of releasing a package of tools for doing useful things with the PHOIBLE data, but it's very low priority and I don't need this issue open to help me remember about it :)
