### ISSUE TITLE
Inventory check

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#99]
allophone <rd> in [sza] in PH

**Comment by drammock** [comment]
I had a glance at this inventory, most look pretty normal, except these few:

| Phoneme | Allophones  |
|:-------:|:-----------:|
|   ɟ     |        ɟ ɟʑ |
|   r     |  r j̃ w̃ ɾ |
|   c     |    c c̚ cɕ |
|   ɔ     |       ɔ ɔ̃ |
|   ɔ̃   |  ɔ̃ ɔ̃ ɔ̃ |
|  ˀj     |      ˀj rd |

**Comment by bambooforest** [comment]
i'll look into these. will update you about segmentation at the next meeting as well.

**Comment by bambooforest** [comment]
@drammock -- this seems to be because of the aggregation script:

ɔ̃	ɔ̃ ɔ̃ ɔ̃	... but this is weird

<ɔ̃> is the last phoneme in the inventory:

https://github.com/phoible/dev/blob/master/raw-data/PH/phoible_inventories.tsv#L6228

and it seems like 

https://github.com/phoible/dev/blob/master/aggregate-raw-data.R#L73-L76

fills in the blanks and then generates extra allophones given the two extra blank lines between inventories.

Regarding "ɟ	ɟ ɟʑ	should be dʑ not ɟʑ" -- the source says:

"In syllable initial position the voiceless lamino-palatal stop /c/, and the voiced /j/ are slightly affricated" (page 50).

OK?

I'll fix the other ones.

**Comment by drammock** [comment]
affricated ɟ should be ɟʝ not ɟʑ

The duplication of ɔ̃ might be fixed by using `blank_lines_skip=TRUE` when the raw data is read in.

**Comment by bambooforest** [comment]
@drammock 

Current code uses the flag you suggest:

https://github.com/phoible/dev/blob/master/aggregate-raw-data.R#L73

but it doesn't seem to skip blank lines. I think that's because we load them in as NA. Ideas?

**Comment by drammock** [comment]
Problem is that the "blank lines" aren't actually blank, they contain a bunch of tabs.  Which, as you say, are leading to the empty strings between each tab to get imported as NA.  I tested it and if we just delete the tabs in those blank rows between inventories, this problem goes away.  Are you OK with that solution?  It doesn't change the total number of phonemes we end up with from those sources (which it shouldn't) and it probably fixes a bunch of other cases of duplicate allophones that we hadn't noticed before:

```
ph_data %>% filter(LanguageCode == "fwe") %>% filter(Phoneme == "uː")
  Phoneme Allophones Marginal InventoryID Source LanguageCode LanguageName SpecificDialect            FileNames
1      uː   uː uː uː    FALSE         852     ph          fwe          Fwe            <NA> fwe_baumbach1997.pdf
```

**Comment by bambooforest** [comment]
@drammock -- indeed removing those extra tab rows fixes this problem. I will add this to the current branch I'm working on `fix-remaining-inventory-errors`, so I don't introduce merge issues on myself. I will also do this for all the long data formats in TSV.
